name: GitHub Actions Demo

on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo stuff
      run: |
        echo "The job was triggered by event: ${{ github.event_name }}"
        echo "The name of the branch: ${{ github.ref }}"

    - uses: actions/checkout@v3

    - name: List files in the repository
      run: |
        echo "the new actions are deployed"
